Replace Centos references by Rocky Linux
StackStorm/st2packaging-dockerfiles pull request #121
Opened 2024-02-06 12:49 UTC by khaddict

2024-02-06 15:17 UTC, nzlosh commented
@khaddict The docker build has been updated to use the correct tags, can you push an empty to trigger the build process for this PR please?

2024-02-09 08:38 UTC, amanda11 requested changes

2024-02-09 08:38 UTC, amanda11 commented on packagingbuild/README.md
> +- Rocky Linux 8
Should also add Rocky Llinux 9

2024-02-09 10:59 UTC, khaddict commented on packagingbuild/README.md
> +- Rocky Linux 8
Rocky Linux 9 added

2024-02-09 11:53 UTC, nzlosh commented
The builds are passing now that the Jammy fix was merged to master.  @amanda11 the image builds are automated from what I can tell, no need to push them manually https://hub.docker.com/repository/docker/stackstorm/packagingtest/general

2024-02-09 12:44 UTC, amanda11 commented
> The builds are passing now that the Jammy fix was merged to master. @amanda11 the image builds are automated from what I can tell, no need to push them manually https://hub.docker.com/repository/docker/stackstorm/packagingtest/general

OK - that's good. I had notes that previously we had lost the ability to do this due to dockerhub changes - but if its back again that's good.

2024-02-09 12:45 UTC, amanda11 approved these changes
LGTM - thanks for the contribution

2024-02-09 12:47 UTC, merged